### ISSUE TITLE
'BartConstrainedGen' object has no attribute 'postprocess_next_token_scores'

### ISSUE THREAD

**Issue by Sethcat** [raspberryice/gen-arg#1]
Thanks for sharing the code! 

I could successfully training model on the wikievents dataset.  But got the error saying "'BartConstrainedGen' object has no attribute `postprocess_next_token_scores`" when run scripts/test_kairos.sh. 

It seems `postprocess_next_token_scores` method is not include in the `BartConstrainedGen` class (src/genie/constrained_gen.py). Is there something missing in the code or any other cause ? Look forward to your reply!

**Comment by raspberryice** [comment]
Thanks for reporting this! The method was from an old version of the `transformers` library's `GenerationMixin`.I'm checking to see if directly including the method in the `BartConstrainedGen` class fixes the problem.

**Comment by raspberryice** [comment]
Hi Sethcat, 
Can you check if the updated `src/genie/constrained_gen.py` file works for you?

**Comment by Sethcat** [comment]
Thanks ! It works for me.
