### ISSUE TITLE
where the "restrict the vocabulary of words to Vc" mentioned in the paper is reflected in the code?

### ISSUE THREAD

**Issue by chennuo666** [raspberryice/gen-arg#10]
Hi, thanks for sharing code!

I would like to ask where the "restrict the vocabulary of words to Vc" mentioned in the paper is reflected in the code?

In the code, it seems that the token with the highest probability is taken as the result by default.

![image](https://user-images.githubusercontent.com/41822797/135830830-d3100702-e64e-48a7-831f-d459f576f63f.png)

**Comment by raspberryice** [comment]
Hi,
Please see line 172 in the `constrainted_gen.py` file. The function essentially sets all the probability of tokens that do not appear in the input to zero.
