### ISSUE TITLE
Where is the WikiEvents dataset

### ISSUE THREAD

**Issue by KyrieIrving24** [raspberryice/gen-arg#11]

**Comment by raspberryice** [comment]
Hi,
I've updated the README file to include more detailed instructions.

**Comment by KyrieIrving24** [comment]
> Hi, I've updated the README file to include more detailed instructions.

Thank you for your reply，and i have question about the metric。
I dont understand the Coref F1. In the paper，it may mean the offsets match the reference，but in your code，it is equal to informative argument.
Looking forward to your reply！

**Comment by raspberryice** [comment]
The Head F1 metric means that the extracted span's offset matches the reference offset.
The Coref F1 metric checks if the extracted span's offset matches any of the coreferential spans of the reference mention. 
In the code there's a mapping table from every mention -> its information mention. If the extracted span and the reference span map to the same thing under this table, it means that there are coreferential. (In this case, the extracted span and the reference span do not need to be the information mention.)

For the informative argument extraction, the difference is in the training. During training, only the informative argument span is treated as the ground truth. The Head F1 in this case is checking whether the extracted span's offset matches the informative span offset.
