### ISSUE TITLE
The event arguments annotation.

### ISSUE THREAD

**Issue by taolusi** [raspberryice/gen-arg#15]
Since there are coreferential entity mentions in a document, what is the principle to decide which entity mention should be annotated as the argument of an event?
Besides, I find entity coreference clusters stored in split.jsonlines, but I do not find the event coreference clusters. Where are they stored?

**Comment by raspberryice** [comment]
Hi Qingkai,
The argument annotation was done separately so the annotators did not see the coreference chains. We thought this could be a potential problem, so we recommend Coref-F1 or the informative argument F1 for better evaluation.
The event coreference is not available in this version of the dataset and this information is not used by the algorithm.
