### ISSUE TITLE
TapKey Model Missing

### ISSUE THREAD

**Issue by helblazer811** [raspberryice/gen-arg#17]
Hello, 
    I really like this project! I think the TapKey model for event trigger detection is not included in the repository. I would like to use it. I could just be missing it as well. Let me know. Thanks so much!

**Comment by raspberryice** [comment]
Hi helblazer811,
Thanks for bringing this up. I put the TapKey model code at the `tapkey` branch. This includes the training and evaluation code. There is still one important part, namely the pseudo label generation code that is not there yet. I'm planning to check that part and uploaded it next week.

**Comment by raspberryice** [comment]
The pseudo labeling code is now available. All of the event trigger detection code is under the `zs_tagger` directory.

**Comment by helblazer811** [comment]
Thank you so much for all of the help. Great paper!
