### ISSUE TITLE
data process

### ISSUE THREAD

**Issue by Hou-jing** [raspberryice/gen-arg#19]
the data you provide is right??
when I use preprocessed_KAIROS this file ,I don't find the following items which used in dataloader:
'input_token_ids': input_token_ids,
        'input_attn_mask': input_attn_mask,
        'tgt_token_ids': tgt_token_ids,
        'tgt_attn_mask': tgt_attn_mask,
        'doc_key': doc_keys,
![image](https://user-images.githubusercontent.com/75936962/174484707-ef43b93d-73f3-444a-ab69-4f34fbd1998e.png)

**Comment by raspberryice** [comment]
Hi Hou-jing,
The `preprocessed_KAIROS` directory is supposed to be created by the `KAIROS_data_module.py` file and it should contain the tokenized results. It is not where you should put your source data. 
See the `prepare_data` method for details.
![image](https://user-images.githubusercontent.com/14961154/174492646-62835ffb-d1c5-412e-93d4-ebcd70351d21.png)

**Comment by raspberryice** [comment]
If you are not getting this `preprocessed_KAIROS` automatically, you can first run this `prepare_data` separately.

**Comment by Hou-jing** [comment]
Thanks, I understand.

**Comment by Hou-jing** [comment]
Sorry, I come across another question,I can not find Keyword-Based Trigger Extraction Model which mentioned in your paper. Did you put it in on this repository？

**Comment by raspberryice** [comment]
Please check the `tapkey` branch.

**Comment by Hou-jing** [comment]
Thank you, I find it
