### ISSUE TITLE
The Length of Document

### ISSUE THREAD

**Issue by Wangpeiyi9979** [raspberryice/gen-arg#2]
Hi, thanks for your nice work.
When analyzing data, I find many documents are very long. 
I find in your code, the MAX_LENGTH is 424. However, in Figure 4 of the paper:
![image](https://user-images.githubusercontent.com/42565075/115719616-d77f1900-a3ae-11eb-9379-63fed56e4d00.png)
the distance of many informative args is greater than MAX_LENGTH, so many args are not even inputted to the encoder?

**Comment by raspberryice** [comment]
Hi Peiyi, 
The y-axis is in log-scale so it's still a long tail distribution. But you are right in the fact that in the chunking process, some distant arguments may not appear. This is a model limitation and I suppose long-context LMs (such as Longformers) could improve in this case.

**Comment by RunxinXu** [comment]
Hi, what's the MAX_LENGTH you set for the WikiEvent dataset?

**Comment by jeremytanjianle** [comment]
I wonder if since the model is using BART, we may simply switch up to 1024 max length without much re-engineering?

And if we want to use this model for even longer documents, would it be possible to simply switch out the encoder for allenai's Longformer EncoderDecoder model?

**Comment by raspberryice** [comment]
> I wonder if since the model is using BART, we may simply switch up to 1024 max length without much re-engineering?
> 
> And if we want to use this model for even longer documents, would it be possible to simply switch out the encoder for allenai's Longformer EncoderDecoder model?

Yes, you can change the base model BART to another encoder-decoder model that handles long context. The hard-coded max length is only to speed up training on the datasets that I used for the paper.
