### ISSUE TITLE
关于生成时约束词表

### ISSUE THREAD

**Issue by Lilice-r** [raspberryice/gen-arg#23]
请问为何只在wikievents上解码时将词表限制在输入的文本中(MODEL=constrained-gen)，而在RAMS上 没有约束词表？(MODEL=gen)

**Comment by raspberryice** [comment]
scripts/ 下的文件是一个样例，RAMS上也可以设置 model=constrained-gen。

**Comment by Lilice-r** [comment]
> 

请问论文里在RAMS上的结果是约束了词表的还是未约束的呢？

**Comment by raspberryice** [comment]
训练的时候约束与否都可以，测试的时候需要约束词表。
