### ISSUE TITLE
About the evaluation set of ACE

### ISSUE THREAD

**Issue by gnodgnodtonmi** [raspberryice/gen-arg#25]
Hello, thank you for your excellent work.

As mentioned in your paper, `We used two settings for selecting known types: 10 most frequent events types and 8 event types, one from each parent type of the event ontology` and `The evaluation is done on the complete set of event types`. 

Could you please tell me what is the ACE evaluation set used in the results of rows `10 most frequent` and `1 per general type` in Table 8 ?
Does the evaluation set of these experimental settings contain seen event types?

**Comment by raspberryice** [comment]
Hi zhengdong, the dev set and evaluation set are kept are the same with the full ACE dataset. We only reduced the number of training examples by type.
