### ISSUE TITLE
你好想问一下关于任务和数据的问题。

### ISSUE THREAD

**Issue by xinjicong** [raspberryice/gen-arg#26]
你好！想请教一下event_role_KAIROS.json这个文件中，role_type的含义，是每个role可能的实体类型吗？其中像bal、com、mon等类型不是很清楚具体的含义，不知道有没有对应的具体含义或者有什么可以查找到相应解释的方法。

**Comment by raspberryice** [comment]
你好！
BAL，COM，MON是role可能的实体类型, 参考 https://github.com/raspberryice/gen-arg/blob/tapkey/ontology/entity_types.json

**Comment by xinjicong** [comment]
感谢回复！
