### ISSUE TITLE
139 event types in paper vs 149 in csv file

### ISSUE THREAD

**Issue by bablf** [raspberryice/gen-arg#27]
Hi, 

Great paper :+1: 
Quick question, why do you report 139 Event types in your paper but in the clean ontology csv file there are 149 event types. 
And how did you create the aida_cleaned_ontology.csv file? 

Thanks in advance! :hugs:

**Comment by raspberryice** [comment]
Hi Bablf,
Our numbers for the event types are based on the number of types that appear in the dataset. Some of the types are defined in the ontology, but there isn't any labeled data. 

As for the `aida_cleaned_ontology.csv` file, we were part of the AIDA program so we had access to the ontology.

**Comment by bablf** [comment]
ok. Too bad that the ontology hasn't been published yet.
