### ISSUE TITLE
About The Appendix A，B，C and D in "Document-Level Event Argument Extraction by Conditional Generation

### ISSUE THREAD

**Issue by yinazhu** [raspberryice/gen-arg#3]
Hi @raspberryice. I am a loyal reader of the paper "Document-Level Event Argument Extraction by Conditional Generation". I like this paper very much and benefit a lot from it.
       Thanks a lot for your work. I was very interested in your research, but there is A barrier in the process of reading. I tried to find the Appendices A, B, C and D in this paper, but I couldn‘t find them. Can you give me some instructions that provide the addresses for the Appendices A, B, C and D? 
       Thank you again for your work and sharing the code.

**Comment by raspberryice** [comment]
Hi @yinazhu, you can now find the appendix in the repository as a pdf document.
