### ISSUE TITLE
RAMS dataset missing test files

### ISSUE THREAD

**Issue by Sethcat** [raspberryice/gen-arg#5]
In ```scripts/test_rams.sh```, when in ```head eval``` mode, the input file "data/RAMS_1.0/data/test_head.jsonlines" is missing in downloaded rams dataset. Also found missing file of "data/RAMS_1.0/data/test_head_coref.jsonlines". 

Could you upload the above two missing files? Thanks.

**Comment by raspberryice** [comment]
Hi Sethcat,
The dataset is not created by us, we don't want to redistribute the dataset here. We processed the dataset by finding the syntactic head of the argument spans using Spacy similar to the `find_head` function in `utils.py`. Alternatively, I can send you my processed version if you leave your email here.

**Comment by aReyOuok-922** [comment]
> Hi Sethcat, The dataset is not created by us, we don't want to redistribute the dataset here. We processed the dataset by finding the syntactic head of the argument spans using Spacy similar to the `find_head` function in `utils.py`. Alternatively, I can send you my processed version if you leave your email here.

2159836627@qq.com please..

**Comment by raspberryice** [comment]
Hi, 
You can find the processed files at `https://gen-arg-data.s3.us-east-2.amazonaws.com/RAMS/test_head_coref.jsonlines` and `https://gen-arg-data.s3.us-east-2.amazonaws.com/RAMS/test_head.jsonlines` respectively.
