### ISSUE TITLE
tgr-pred-file

### ISSUE THREAD

**Issue by fatimashiri** [raspberryice/gen-arg#9]
Hi, thank you for this amazing work. When we try to test the model with pipeline_scorer it requires tgr-pred-file. The question is how to get this file for kairos dataset?

**Comment by raspberryice** [comment]
Hi fatimashiri,
The "tgr-pred-file" is any output from the trigger extraction model, and the file "pipeline_scorer.py" is meant to evaluate the end-to-end performance. If you are evaluating the argument extraction performance, you can use the "scorer.py" file instead.
